# Site settings
title: 乌托邦
description: "blog.joy-hubs.com"
baseurl: ""
url: "https://blog.joy-hubs.com"

# Author
author:
  name:       采集记忆
  url:        https://blog.joy-hubs.com
  email:      green1893@gmail.com

# Build settings
markdown: kramdown
comments: true

# Assets
sass:
  style: compressed

# Build settings, default theme is minima
#theme: tale
remote_theme: chesterhow/tale

# Gems
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-remote-theme

# Permalinks
permalink: /articles/:title
paginate: 5

include:
  - _pages
exclude:
  - vendor
  - Gemfile
  - Gemfile.lock

# comments support
giscus:
  repo: "green1893/joy-hubs.github.com"
  repo_id: "R_kgDOKYfXmQ"
  category: "Announcements"
  category_id: "DIC_kwDOKYfXmc4CZpxH"
  mapping: 'pathname'
  input_position: 'top'
  theme: 'preferred_color_scheme'
  lang: "zh-CN"